server.port=8080

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=risk-scoring-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.concurrency=8
spring.kafka.listener.poll-timeout=3000

# === LOGGING - VERY IMPORTANT ===
logging.level.com.beast.risk=DEBUG
#logging.level.org.springframework.kafka=DEBUG
logging.level.root=INFO

# Show everything during development
spring.main.banner-mode=console

# Micrometer / Actuator
management.endpoints.web.exposure.include=*
management.metrics.enable.all=true

# Disable OTLP export for local run (we can enable later with collector)
management.otlp.metrics.export.enabled=false
management.otlp.traces.export.enabled=false
management.metrics.export.otlp.enabled=false

# Ollama Configuration
ollama.url=http://localhost:11434/api/generate
ollama.model=llama3.2:3b
ollama.temperature=0.3
ollama.format=json
ollama.stream=false

spring.task.scheduling.pool.size=1